# Generated by Django 5.1.7 on 2025-03-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_alter_codeforcesuser_current_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeforcesuser',
            name='current_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='max_rating',
            field=models.IntegerField(default=0),
        ),
    ]
