# Generated by Django 5.1.7 on 2025-03-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_alter_codeforcesuser_current_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeforcesuser',
            old_name='image',
            new_name='profile_picture',
        ),
    ]
